<!DOCTYPE html>
<html>

<head>

<title>
SecureBiz AI Security Report
</title>


<style>

body {

    font-family: DejaVu Sans, sans-serif;

    color:#1f2937;

    font-size:14px;

}


.header {

    text-align:center;

    margin-bottom:30px;

}


.logo {

    font-size:32px;

    font-weight:bold;

    color:#059669;

}


.subtitle {

    color:#64748b;

}


.website {

    margin-top:15px;

    font-size:16px;

    font-weight:bold;

}



.card {

    border:1px solid #e5e7eb;

    border-radius:12px;

    padding:20px;

    margin-top:20px;

}



.score {

    text-align:center;

    font-size:48px;

    font-weight:bold;

    color:#059669;

}



.badge {

    padding:6px 12px;

    border-radius:20px;

    font-weight:bold;

}



.low {

    color:#059669;

}


.medium {

    color:#ca8a04;

}


.high {

    color:#dc2626;

}



.section-title {

    font-size:20px;

    font-weight:bold;

    margin-top:30px;

    border-bottom:1px solid #ddd;

    padding-bottom:8px;

}



.item {

    padding:10px;

    border-bottom:1px solid #eee;

}



.success {

    color:#059669;

    font-weight:bold;

}



.warning {

    color:#ca8a04;

    font-weight:bold;

}



.finding {

    background:#f8fafc;

    border-radius:8px;

    padding:15px;

    margin-top:12px;

}



.footer {

    margin-top:40px;

    text-align:center;

    color:#64748b;

    font-size:12px;

}



</style>


</head>



<body>



<div class="header">


<div class="logo">

SECUREBIZ AI

</div>


<div class="subtitle">

AI-Powered Cybersecurity Assessment

</div>


<div class="website">

{{ $scan->website }}

</div>


</div>





<div class="card">


<div class="section-title">

Security Score

</div>


<div class="score">

{{ $scan->score }}/100

</div>


<p>

Grade:

<strong>

{{ $scan->grade }}

</strong>

</p>



<p>

Risk:

<strong
class="
@if($scan->risk == 'Low')
low

@elseif($scan->risk == 'Medium')
medium

@else
high

@endif
"
>

{{ $scan->risk }}

</strong>


</p>



</div>







<div class="section-title">

Security Checks

</div>



<div class="card">


@foreach($scan->checks ?? [] as $check)


<div class="item">


@if($check['status']=="Passed")


<span class="success">

PASS -

</span>


@else


<span class="warning">

WARNING -

</span>


@endif



{{ $check['name'] }}


:

{{ $check['status'] }}


</div>


@endforeach


</div>








<div class="section-title">

Security Findings

</div>



@if(!empty($scan->vulnerabilities))


@foreach($scan->vulnerabilities as $item)


<div class="finding">


<h3>

{{ $item['title'] ?? 'Unknown Finding' }}

</h3>


<p>

<strong>
Severity:
</strong>

{{ $item['severity'] ?? 'Unknown' }}

</p>



<p>

{{ $item['impact'] ?? '' }}

</p>



<p>

<strong>
Fix:
</strong>

{{ $item['fix'] ?? '' }}

</p>


</div>



@endforeach


@else


<div class="card">

No vulnerabilities detected.

</div>


@endif







<div class="section-title">

Recommendations

</div>


<div class="card">


@foreach($scan->recommendations ?? [] as $recommendation)


<div class="item">


-

{{ $recommendation }}


</div>


@endforeach


</div>








<div class="section-title">

Detected Technologies

</div>


<div class="card">


@foreach($scan->technologies ?? [] as $technology)


<div class="item">


{{ $technology }}


</div>


@endforeach


</div>









@if($scan->ai_analysis)


<div class="section-title">

AI Security Analysis

</div>


<div class="card">


{{ $scan->ai_analysis }}


</div>


@endif






<div class="footer">

Generated by SecureBiz AI Security Scanner

</div>



</body>

</html>